version: '2'
services:
  proftpd:
    image: clementperon/proftpd
    container_name: proftpd
    volumes:
      - ./proftpd/config:/config
      - ./data/ftp:/data
      - certificates:/etc/letsencrypt:ro
    ports:
      - 990:990
      - 49152-49407:49152-49407
